### ISSUE TITLE
PBNS: Project Basic Navigation Setup

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/meta-learnings#16]
## Script in workspace

无论是之前做 pipeline 还是最近做新的项目，发现一个项目有许多相关的链接资源，比如

* homespace -> slave label(jenkins) -> slave name(jenkins) -> server ip(aws) -> actions 
* project page(gist) -> server ips(aws/terminal) -> git repo(github/stash) -> pipeline(jenkins/travis)

好的命名+保存书签只能解决在浏览器这部分的需求，实际上 navigate 这个过程还是我们自己在操作，这就很坑了，而且有时还要切换多个窗口（Windows 你懂得），效率很低。因此萌生了这个做一个命令行工具的想法，开发的时候一定要有产品的意识，我这个东西是有使用场景的，我最希望得到它的什么信息？

* Phase 1：可以 hardcode 一些数据（强行从网页抽取然后保存成静态 json），实现命令行基本功能
* Phase 2：User Experience
* Phase 3：把数据做成实时的抽取
* Phase 4：这些数据其实就是一个表格，多个项目甚至都是一样的，是否可以考虑做成更加模板化的东西
* Phase 5：资源梯次展开。比如说你拿到了服务器的 ip，由这个 key 又可以索引到它更多的数据。

## concerns

* 数据正确性如何验证？（你怎么知道你抽的就是对的）「楼下的观众朋友我知道你们中有人会问这个问题 ~」
* 数据来源如何验证？（换句话说，你说你拿到了这个信息，那我会问你，这个信息你是在哪里拿到的？）

**Comment by JimmyLv** [comment]
啊哈，Cool

**Comment by linesh-simplicity** [comment]
啥 jb 玩意。close #16

**Comment by linesh-simplicity** [comment]
closes #16

**Comment by linesh-simplicity** [comment]
closed #16

**Comment by JimmyLv** [comment]
这不是很好么 咋就啥玩意儿了

**Comment by linesh-simplicity** [comment]
$****p 应该是比较特别的例子，一个组可能要处理多个项目。过去的一周发现，其实对于单一的项目来说，简单直接的 脚本就可以解决了，比如 `go sys`, `go jira`。不过倒是发现，每个项目可能都有类似的资源，比如导航到 sys/uat 环境、发布部署的脚本、看板（Jira/Trello/...）、代码库、原型图。。。等，这些倒是可以共用的。我突然又发现可以提供工具来做这个事情啊！

**Comment by linesh-simplicity** [comment]
想象的 API：

```bash
npm install project-resources -g

project register 
version control: https://github.com/linesh-simplicity/elegant-mac
kanban: https://trello.com/b/oN99a6BC/week-1-basics-aem-training
# done

# registered 'company' command
company vcs # go to https://github.com/linesh-simplicity/elegant-mac
company kanban # go to https://trello.com/b/oN99a6BC/week-1-basics-aem-training
```

**Comment by JimmyLv** [comment]
跨项目确实是一个很头疼的问题，但是我觉得通过命令行打开算是一种方式，最终的目的或者是说背后的需求是快速得到想要的信息。

那我可不可以做一个 website 或者是 Chrome extension，就只展示所有（或者是可 config）我想要看的内容。

只要内容/信息 as APIs 一切就都好办了，比如说我就一键获取所有 Pipeline 的红绿状态，或者是打开卡号。

$> a(lfred) status #红的绿的？
$> s(tash) status
$> j(ira) status

Best Regards,
Jimmy.

**Comment by linesh-simplicity** [comment]
好主意！开搞吧少年！

我觉得你说到点了。这类需求背后目的是要 **快速得到想要的信息**。至于得到信息是想要完成什么工作，这个工作流本身能不能优化，则是另外的问题域了。

**Comment by JimmyLv** [comment]
@linesh-simplicity 在 Chrome 上面找到个很好用的插件，DA 亲测可用并且结合 shortcut 很无敌啊！https://chrome.google.com/webstore/detail/yet-another-jenkins-notif/cimdjdaglanfkpfpoemjkfkmjgkmahpg?hl=en

**Comment by linesh-simplicity** [comment]
噗哈哈哈哈，赞赞赞。又解决了一个需求…

**Comment by JimmyLv** [comment]
你说得非常对啊，「快速让整个 Team 得到想要的信息」
